[pytest]
DJANGO_SETTINGS_MODULE = froide_evidencecollection.tests.settings

filterwarnings =
    ignore::DeprecationWarning:(?!froide_evidencecollection).*
    ignore::PendingDeprecationWarning:(?!froide_evidencecollection).*
