# Generated by Django 4.2.16 on 2024-11-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("froide_evidencecollection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="title",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evidence",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="froide_evidencecollection.evidencearea",
                verbose_name="Evidence Area",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="froide_evidencecollection.person",
                verbose_name="Person",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="quality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="froide_evidencecollection.quality",
                verbose_name="Evidence Quality",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="froide_evidencecollection.source",
                verbose_name="Quelle",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="froide_evidencecollection.evidencetype",
                verbose_name="Evidence Type",
            ),
        ),
    ]
