# Generated by Django 4.2.16 on 2025-04-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0002_evidence_title_alter_evidence_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='froide_evidencecollection.source', verbose_name='Source'),
        ),
    ]
