# Generated by Django 4.2.16 on 2025-04-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georegion', '0011_georegion_invalid_on'),
        ('froide_evidencecollection', '0003_alter_evidence_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'affiliation',
                'verbose_name_plural': 'affiliations',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'function',
                'verbose_name_plural': 'functions',
            },
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='PersonOrOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='review comment')),
                ('affiliations', models.ManyToManyField(related_name='persons', through='froide_evidencecollection.Affiliation', to='froide_evidencecollection.institution', verbose_name='affiliations')),
                ('regions', models.ManyToManyField(to='georegion.georegion', verbose_name='regions')),
            ],
            options={
                'verbose_name': 'person/organization',
                'verbose_name_plural': 'persons/organizations',
            },
        ),
        migrations.AddField(
            model_name='affiliation',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='froide_evidencecollection.function', verbose_name='function'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='froide_evidencecollection.institution', verbose_name='institution/party level'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='person_or_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='froide_evidencecollection.personororganization', verbose_name='person/organization'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('person_or_organization', 'institution', 'function')},
        ),
    ]
