# Generated by Django 4.2.16 on 2025-05-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0004_affiliation_attributionbasis_distributionchannel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='georegion',
        ),
        migrations.RemoveField(
            model_name='person',
            name='highest_position',
        ),
        migrations.RemoveField(
            model_name='person',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.RemoveField(
            model_name='source',
            name='public_body',
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.DeleteModel(
            name='EvidenceArea',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Quality',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
