# Generated by Django 4.2.16 on 2025-05-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0050_alter_publicbody_email'),
        ('froide_evidencecollection', '0005_remove_person_georegion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvidenceNew',
            new_name='Evidence',
        ),
        migrations.RenameModel(
            old_name='SourceNew',
            new_name='Source',
        ),
    ]
