# Generated by Django 4.2.16 on 2025-06-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0006_rename_evidencenew_evidence_rename_sourcenew_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'verbose_name': 'piece of evidence', 'verbose_name_plural': 'pieces of evidence'},
        ),
    ]
