# Generated by Django 5.2.1 on 2025-06-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0008_rename_fdgofeature_evidencecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=255, upload_to='attachments', verbose_name='file'),
        ),
    ]
