# Generated by Django 5.2.1 on 2025-08-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0010_actor_attributionproblem_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personororganization',
            name='affiliations',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='source',
        ),
        migrations.RemoveField(
            model_name='source',
            name='attribution_bases',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='distribution_channels',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='spread_level',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='type',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='personororganization',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='source',
            name='persons_or_organizations',
        ),
        migrations.RemoveField(
            model_name='source',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='AttributionBasis',
        ),
        migrations.DeleteModel(
            name='DistributionChannel',
        ),
        migrations.DeleteModel(
            name='EvidenceCategory',
        ),
        migrations.DeleteModel(
            name='SpreadLevel',
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='PersonOrOrganization',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
