# Generated by Django 5.2.1 on 2025-08-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0011_remove_personororganization_affiliations_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AffiliationNew',
            new_name='Affiliation',
        ),
        migrations.RenameModel(
            old_name='AttachmentNew',
            new_name='Attachment',
        ),
        migrations.RenameModel(
            old_name='EvidenceNew',
            new_name='Evidence',
        ),
    ]
