# Generated by Django 5.2.1 on 2025-08-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0012_rename_affiliationnew_affiliation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='actor_ptr',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='institutional_level',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='status',
        ),
        migrations.RemoveField(
            model_name='person',
            name='actor_ptr',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='originators',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='related_actors',
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
