# Generated by Django 5.2.1 on 2025-08-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0012_rename_affiliationnew_affiliation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parliament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_id', models.PositiveIntegerField(unique=True, verbose_name='abgeordnetenwatch.de ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('fraction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='froide_evidencecollection.organization', verbose_name='fraction')),
            ],
            options={
                'verbose_name': 'parliament',
                'verbose_name_plural': 'parliaments',
            },
        ),
    ]
