# Generated by Django 5.2.1 on 2025-08-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0013_remove_organization_actor_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
