# Generated by Django 5.2.1 on 2025-08-20 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0013_parliament'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_id', models.PositiveIntegerField(unique=True, verbose_name='abgeordnetenwatch.de ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='froide_evidencecollection.parliament', verbose_name='parliament')),
            ],
            options={
                'verbose_name': 'parliament period',
                'verbose_name_plural': 'parliament periods',
                'unique_together': {('parliament', 'start_date', 'end_date')},
            },
        ),
    ]
