# Generated by Django 5.2.1 on 2025-08-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0015_actor_importexportrun_role_attachment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='is_synced',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(synced_at__isnull=True, then=models.Value(False)), models.When(synced_at__gte=models.F('updated_at'), then=models.Value(True)), default=models.Value(False)), output_field=models.BooleanField(), verbose_name='is synced'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_synced',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(synced_at__isnull=True, then=models.Value(False)), models.When(synced_at__gte=models.F('updated_at'), then=models.Value(True)), default=models.Value(False)), output_field=models.BooleanField(), verbose_name='is synced'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_synced',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(synced_at__isnull=True, then=models.Value(False)), models.When(synced_at__gte=models.F('updated_at'), then=models.Value(True)), default=models.Value(False)), output_field=models.BooleanField(), verbose_name='is synced'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_synced',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(synced_at__isnull=True, then=models.Value(False)), models.When(synced_at__gte=models.F('updated_at'), then=models.Value(True)), default=models.Value(False)), output_field=models.BooleanField(), verbose_name='is synced'),
        ),
    ]
