# Generated by Django 5.2.1 on 2025-09-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0016_affiliation_is_synced_organization_is_synced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='sync_uuid',
            field=models.UUIDField(editable=False, unique=True, verbose_name='sync UUID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sync_uuid',
            field=models.UUIDField(editable=False, unique=True, verbose_name='sync UUID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sync_uuid',
            field=models.UUIDField(editable=False, unique=True, verbose_name='sync UUID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='sync_uuid',
            field=models.UUIDField(editable=False, unique=True, verbose_name='sync UUID'),
        ),
    ]
