# Generated by Django 5.2.1 on 2025-09-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0017_alter_affiliation_sync_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='last_synced_state',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_synced_state',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='last_synced_state',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='role',
            name='last_synced_state',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
