# Generated by Django 5.2.1 on 2025-10-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0018_affiliation_last_synced_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='end_date_string',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='end date (string)'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='reference_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='reference URL'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='start_date_string',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='start date (string)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mimetype',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='mimetype'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='citation',
            field=models.TextField(blank=True, default='', verbose_name='citation'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='primary_source_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='primary source URL'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='reference_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='reference (URL)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='title'),
        ),
    ]
