# Generated by Django 5.2.1 on 2025-10-15 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0019_alter_affiliation_end_date_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importexportrun',
            name='source',
            field=models.CharField(choices=[('FE', 'Froide EvidenceCollection'), ('NC', 'NocoDB'), ('AW', 'abgeordnetenwatch.de')], max_length=2, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='importexportrun',
            name='target',
            field=models.CharField(choices=[('FE', 'Froide EvidenceCollection'), ('NC', 'NocoDB'), ('AW', 'abgeordnetenwatch.de')], max_length=2, verbose_name='target'),
        ),
        migrations.CreateModel(
            name='Parliament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_id', models.PositiveIntegerField(unique=True, verbose_name='abgeordnetenwatch.de ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('fraction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='froide_evidencecollection.organization', verbose_name='fraction')),
            ],
            options={
                'verbose_name': '🏛️ Parliament',
                'verbose_name_plural': '🏛️ Parliaments',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_id', models.PositiveIntegerField(unique=True, verbose_name='abgeordnetenwatch.de ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='froide_evidencecollection.parliament', verbose_name='parliament')),
            ],
            options={
                'verbose_name': '🏛️ Election',
                'verbose_name_plural': '🏛️ Elections',
                'abstract': False,
                'unique_together': {('parliament', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='LegislativePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_id', models.PositiveIntegerField(unique=True, verbose_name='abgeordnetenwatch.de ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('reference_url', models.URLField(blank=True, default='', max_length=500, verbose_name='reference URL')),
                ('election', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legislative_period', to='froide_evidencecollection.election', verbose_name='election')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislative_periods', to='froide_evidencecollection.parliament', verbose_name='parliament')),
            ],
            options={
                'verbose_name': '🏛️ Legislative period',
                'verbose_name_plural': '🏛️ Legislative periods',
                'abstract': False,
                'unique_together': {('parliament', 'start_date', 'end_date')},
            },
        ),
    ]
