# Generated by Django 5.2.1 on 2025-10-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0020_alter_importexportrun_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importexportrun',
            name='source',
            field=models.CharField(choices=[('FE', 'Froide EvidenceCollection'), ('NC', 'NocoDB'), ('AW', 'abgeordnetenwatch.de'), ('WD', 'Wikidata')], max_length=2, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='importexportrun',
            name='target',
            field=models.CharField(choices=[('FE', 'Froide EvidenceCollection'), ('NC', 'NocoDB'), ('AW', 'abgeordnetenwatch.de'), ('WD', 'Wikidata')], max_length=2, verbose_name='target'),
        ),
    ]
