# Generated by Django 5.2.1 on 2025-10-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0021_alter_importexportrun_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislativeperiod',
            name='reference_url',
        ),
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='legislativeperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
    ]
