# Generated by Django 5.2.13 on 2026-05-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0022_remove_legislativeperiod_reference_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='is_synced',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_synced',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_synced',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_synced',
        ),
    ]
