# Generated by Django 5.2.10 on 2026-06-15 14:54

import django.db.models.deletion
import froide_evidencecollection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0023_remove_affiliation_is_synced_and_more'),
        ('georegion', '0013_alter_georegion_region_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('custom_label', models.CharField(max_length=255, verbose_name='label')),
                ('is_main_topic', models.BooleanField(default=False, verbose_name='is main topic')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=100, unique=True, verbose_name='lemma')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('surface_forms', models.JSONField(blank=True, default=dict, verbose_name='surface forms')),
                ('custom_label', models.CharField(blank=True, default='', max_length=100, verbose_name='custom label')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('df', models.PositiveIntegerField(default=0, verbose_name='document frequency')),
                ('salience_max', models.FloatField(default=0.0, verbose_name='max salience')),
                ('salience_mean', models.FloatField(default=0.0, verbose_name='mean salience')),
                ('fit_at', models.DateTimeField(verbose_name='fitted at')),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'keyword group',
                'verbose_name_plural': 'keyword groups',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bertopic_id', models.SmallIntegerField(blank=True, help_text='Cluster id assigned by BERTopic in the most recent fit. -1 marks the outlier cluster. Not stable across refits.', null=True, verbose_name='BERTopic ID')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='label')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('keywords', models.JSONField(default=list, verbose_name='keywords')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='evidence count')),
                ('fit_at', models.DateTimeField(verbose_name='fitted at')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ['-size', 'bertopic_id'],
            },
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='attribution_problems',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='attribution_evidence',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='attribution_justification',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='legal_assessment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='primary_source_info',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='primary_source_url',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='publishing_date',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='reference_info',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='reference_url',
        ),
        migrations.AddField(
            model_name='evidence',
            name='slug',
            field=models.SlugField(default='', max_length=10, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='topic_fit_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='topic fitted at'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='topic_reassigned',
            field=models.BooleanField(default=False, help_text='True if this evidence was an HDBSCAN outlier in the most recent fit and was moved into its topic by outlier reduction, rather than being a core cluster member.', verbose_name='topic reassigned from outlier'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='topic_x',
            field=models.FloatField(blank=True, null=True, verbose_name='topic x'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='topic_y',
            field=models.FloatField(blank=True, null=True, verbose_name='topic y'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='name hash'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='name hash'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='external ID'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='external ID'),
        ),
        migrations.AlterField(
            model_name='importexportrun',
            name='source',
            field=models.CharField(choices=[('FE', 'Froide EvidenceCollection'), ('NC', 'NocoDB'), ('AW', 'abgeordnetenwatch.de'), ('WD', 'Wikidata'), ('JS', 'JSON dump')], max_length=2, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='importexportrun',
            name='target',
            field=models.CharField(choices=[('FE', 'Froide EvidenceCollection'), ('NC', 'NocoDB'), ('AW', 'abgeordnetenwatch.de'), ('WD', 'Wikidata'), ('JS', 'JSON dump')], max_length=2, verbose_name='target'),
        ),
        migrations.CreateModel(
            name='EvidenceMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footnote', models.CharField(blank=True, default='', max_length=255, verbose_name='footnote')),
                ('chapter_structure', models.JSONField(default=list, verbose_name='chapter structure')),
                ('citation', models.TextField(blank=True, default='', verbose_name='citation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='froide_evidencecollection.category', verbose_name='category')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='froide_evidencecollection.chapter', verbose_name='chapter')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='froide_evidencecollection.evidence', verbose_name='evidence')),
            ],
            options={
                'verbose_name': 'evidence mention',
                'verbose_name_plural': 'evidence mentions',
                'ordering': ['footnote'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='evidences', to='froide_evidencecollection.keyword', verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='froide_evidencecollection.keywordgroup', verbose_name='group'),
        ),
        migrations.CreateModel(
            name='PoliticalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('type', models.CharField(choices=[('mandate', 'Mandate'), ('parliament', 'Parliament'), ('party', 'Party')], max_length=10, verbose_name='type')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('start_source_url', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='start date source URL')),
                ('end_source_url', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='end date source URL')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comment')),
                ('institutional_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='froide_evidencecollection.institutionallevel', verbose_name='institutional level')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='political_positions', to='froide_evidencecollection.organization', verbose_name='organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='political_positions', to='froide_evidencecollection.person', verbose_name='person')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georegion.georegion', verbose_name='region')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='froide_evidencecollection.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'political position',
                'verbose_name_plural': 'political positions',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('youtube', 'YouTube')], max_length=20, verbose_name='platform')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('platform_user_id', models.CharField(blank=True, default='', max_length=255, verbose_name='platform user ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='display name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL')),
                ('is_verified', models.BooleanField(blank=True, null=True, verbose_name='is verified')),
                ('follower_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='follower count')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='collected_at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='froide_evidencecollection.actor', verbose_name='actor')),
            ],
            options={
                'verbose_name': 'social media account',
                'verbose_name_plural': 'social media accounts',
                'ordering': ('platform', 'username'),
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_post_id', models.CharField(max_length=255, verbose_name='platform post ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('text', models.TextField(blank=True, default='', verbose_name='text')),
                ('title', models.TextField(blank=True, default='', verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('caption', models.TextField(blank=True, default='', verbose_name='caption')),
                ('view_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='view count')),
                ('like_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='like count')),
                ('comment_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='comment count')),
                ('is_comment_disabled', models.BooleanField(blank=True, null=True, verbose_name='comments disabled')),
                ('share_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='share count')),
                ('reactions', models.JSONField(blank=True, null=True, verbose_name='reactions')),
                ('unresolved_redistribution', models.JSONField(blank=True, help_text='Reference to a redistributed post that lacks a stable platform post ID and so could not be linked via `redistributes` (e.g. a Telegram hidden forward). Stored verbatim from the source.', null=True, verbose_name='unresolved redistribution')),
                ('user_snapshot', models.JSONField(blank=True, null=True, verbose_name='user snapshot')),
                ('raw', models.JSONField(verbose_name='raw payload')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='froide_evidencecollection.socialmediaaccount', verbose_name='account')),
                ('redistributes', models.ForeignKey(blank=True, help_text='Post whose content this post redistributes (repost, quote, forward, …).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redistributed_by', to='froide_evidencecollection.socialmediapost', verbose_name='redistributed post')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='froide_evidencecollection.socialmediapost', verbose_name='reply to')),
            ],
            options={
                'verbose_name': 'social media post',
                'verbose_name_plural': 'social media posts',
            },
            bases=(froide_evidencecollection.models.EvidenceSource, models.Model),
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('file', models.FileField(blank=True, max_length=255, upload_to='post_media', verbose_name='file')),
                ('source_path', models.CharField(blank=True, default='', max_length=512, verbose_name='source path')),
                ('description', models.TextField(blank=True, default='', help_text='Textual description of what the image/video shows.', verbose_name='description')),
                ('transcript_file', models.FileField(blank=True, help_text='Full transcript (e.g. SRT), kept as backup; not searched.', max_length=255, upload_to='post_media', verbose_name='transcript file')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='froide_evidencecollection.socialmediapost', verbose_name='post')),
            ],
            options={
                'verbose_name': 'post video',
                'verbose_name_plural': 'post videos',
            },
        ),
        migrations.CreateModel(
            name='PostScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('file', models.FileField(blank=True, max_length=255, upload_to='post_media', verbose_name='file')),
                ('source_path', models.CharField(blank=True, default='', max_length=512, verbose_name='source path')),
                ('description', models.TextField(blank=True, default='', help_text='Textual description of what the image/video shows.', verbose_name='description')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='froide_evidencecollection.socialmediapost', verbose_name='post')),
            ],
            options={
                'verbose_name': 'post screenshot',
                'verbose_name_plural': 'post screenshots',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('file', models.FileField(blank=True, max_length=255, upload_to='post_media', verbose_name='file')),
                ('source_path', models.CharField(blank=True, default='', max_length=512, verbose_name='source path')),
                ('description', models.TextField(blank=True, default='', help_text='Textual description of what the image/video shows.', verbose_name='description')),
                ('content_text', models.TextField(blank=True, default='', help_text='On-screen text of the image (searched). Import-filled; correct it via the override field.', verbose_name='content text')),
                ('content_text_override', models.TextField(blank=True, default='', help_text='Curator correction of the content text. Blank falls back to the imported value. Preserved across re-imports.', verbose_name='content text (corrected)')),
                ('is_related_to_text', models.BooleanField(blank=True, help_text="Whether the image relates to the post's text. Import-filled.", null=True, verbose_name='related to post text')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='froide_evidencecollection.socialmediapost', verbose_name='post')),
            ],
            options={
                'verbose_name': 'post image',
                'verbose_name_plural': 'post images',
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='social_media_post',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='froide_evidencecollection.socialmediapost', verbose_name='social media post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='froide_evidencecollection.topic', verbose_name='topic'),
        ),
        migrations.CreateModel(
            name='VideoExcerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('start', models.DurationField(blank=True, null=True, verbose_name='start')),
                ('end', models.DurationField(blank=True, null=True, verbose_name='end')),
                ('text', models.TextField(blank=True, default='', help_text='Transcript excerpt text (searched). Import-filled.', verbose_name='text')),
                ('text_override', models.TextField(blank=True, default='', help_text='Curator correction of the excerpt text. Blank falls back to the imported value. Preserved across re-imports.', verbose_name='text (corrected)')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='froide_evidencecollection.postvideo', verbose_name='video')),
            ],
            options={
                'verbose_name': 'video excerpt',
                'verbose_name_plural': 'video excerpts',
                'ordering': ['video', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='AttributionProblem',
        ),
        migrations.AddConstraint(
            model_name='socialmediaaccount',
            constraint=models.UniqueConstraint(fields=('platform', 'platform_user_id'), name='unique_social_media_account'),
        ),
        migrations.AddConstraint(
            model_name='socialmediapost',
            constraint=models.UniqueConstraint(fields=('account', 'platform_post_id'), name='unique_post_per_account'),
        ),
        migrations.AddConstraint(
            model_name='postvideo',
            constraint=models.UniqueConstraint(condition=models.Q(('source_path', ''), _negated=True), fields=('post', 'source_path'), name='unique_video_per_post_source'),
        ),
        migrations.AddConstraint(
            model_name='postscreenshot',
            constraint=models.UniqueConstraint(condition=models.Q(('source_path', ''), _negated=True), fields=('post', 'source_path'), name='unique_screenshot_per_post_source'),
        ),
        migrations.AddConstraint(
            model_name='postimage',
            constraint=models.UniqueConstraint(condition=models.Q(('source_path', ''), _negated=True), fields=('post', 'source_path'), name='unique_image_per_post_source'),
        ),
        migrations.AddConstraint(
            model_name='videoexcerpt',
            constraint=models.UniqueConstraint(fields=('video', 'order'), name='unique_excerpt_order_per_video'),
        ),
    ]
