# Generated by Django 5.2.13 on 2026-05-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0023_remove_affiliation_is_synced_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='external_id',
        ),
    ]
