# Generated by Django 5.2.10 on 2026-06-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0024_category_chapter_keyword_keywordgroup_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='post_media', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='postscreenshot',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='post_media', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='post_media', verbose_name='file'),
        ),
    ]
