# Generated by Django 5.2.13 on 2026-06-19 10:11

import django.db.models.deletion
import froide_evidencecollection.models
import froide_evidencecollection.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0024_remove_actor_external_id_remove_actor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('youtube', 'YouTube')], max_length=20, verbose_name='platform')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('platform_user_id', models.CharField(blank=True, default='', max_length=255, verbose_name='platform user ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='display name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL')),
                ('is_verified', models.BooleanField(blank=True, null=True, verbose_name='is verified')),
                ('follower_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='follower count')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='collected_at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='froide_evidencecollection.actor', verbose_name='actor')),
            ],
            options={
                'verbose_name': 'social media account',
                'verbose_name_plural': 'social media accounts',
                'ordering': ('platform', 'username'),
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(blank=True, max_length=255, null=True, storage=froide_evidencecollection.storage.OverwriteStorage(), upload_to=froide_evidencecollection.storage.post_screenshot_path, verbose_name='screenshot')),
                ('screenshot_source_path', models.CharField(blank=True, default='', max_length=512, verbose_name='screenshot source path')),
                ('image_source_path', models.CharField(blank=True, default='', max_length=512, verbose_name='image source path')),
                ('image_description', models.TextField(blank=True, default='', help_text='Textual description (alt text) of what the image shows.', verbose_name='image description')),
                ('video_source_path', models.CharField(blank=True, default='', max_length=512, verbose_name='video source path')),
                ('transcription', models.TextField(blank=True, default='', help_text='Full verbatim video transcript; display/backup.', verbose_name='transcription')),
                ('platform_post_id', models.CharField(max_length=255, verbose_name='platform post ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('text', models.TextField(blank=True, default='', verbose_name='text')),
                ('title', models.TextField(blank=True, default='', verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('view_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='view count')),
                ('like_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='like count')),
                ('comment_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='comment count')),
                ('is_comment_disabled', models.BooleanField(blank=True, null=True, verbose_name='comments disabled')),
                ('share_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='share count')),
                ('reactions', models.JSONField(blank=True, null=True, verbose_name='reactions')),
                ('unresolved_redistribution', models.JSONField(blank=True, help_text='Reference to a redistributed post that lacks a stable platform post ID and so could not be linked via `redistributes` (e.g. a Telegram hidden forward). Stored verbatim from the source.', null=True, verbose_name='unresolved redistribution')),
                ('user_snapshot', models.JSONField(blank=True, null=True, verbose_name='user snapshot')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='froide_evidencecollection.socialmediaaccount', verbose_name='account')),
                ('redistributes', models.ForeignKey(blank=True, help_text='Post whose content this post redistributes (repost, quote, forward, …).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redistributed_by', to='froide_evidencecollection.socialmediapost', verbose_name='redistributed post')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='froide_evidencecollection.socialmediapost', verbose_name='reply to')),
            ],
            options={
                'verbose_name': 'social media post',
                'verbose_name_plural': 'social media posts',
            },
            bases=(froide_evidencecollection.models.EvidenceSource, models.Model),
        ),
        migrations.AddConstraint(
            model_name='socialmediaaccount',
            constraint=models.UniqueConstraint(fields=('platform', 'platform_user_id'), name='unique_social_media_account'),
        ),
        migrations.AddConstraint(
            model_name='socialmediapost',
            constraint=models.UniqueConstraint(fields=('account', 'platform_post_id'), name='unique_post_per_account'),
        ),
    ]
