# Generated by Django 5.2.10 on 2026-04-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0024_populate_name_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('tiktok', 'TikTok'), ('x', 'X'), ('youtube', 'YouTube')], max_length=20, verbose_name='platform')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('platform_user_id', models.CharField(blank=True, default='', max_length=255, verbose_name='platform user ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='display name')),
                ('bio', models.TextField(blank=True, default='', verbose_name='bio')),
                ('profile_url', models.URLField(blank=True, default='', max_length=500, verbose_name='profile URL')),
                ('profile_pic_url', models.URLField(blank=True, default='', max_length=500, verbose_name='profile picture URL')),
                ('is_verified', models.BooleanField(blank=True, null=True, verbose_name='is verified')),
                ('follower_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='follower count')),
                ('profile_retrieved_at', models.DateTimeField(blank=True, null=True, verbose_name='profile retrieved at')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='froide_evidencecollection.actor', verbose_name='actor')),
            ],
            options={
                'verbose_name': 'social media account',
                'verbose_name_plural': 'social media accounts',
                'ordering': ('platform', 'username'),
            },
        ),
        migrations.AddConstraint(
            model_name='socialmediaaccount',
            constraint=models.UniqueConstraint(fields=('platform', 'username'), name='unique_social_media_account'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_evidence', to='froide_evidencecollection.socialmediaaccount', verbose_name='posted by'),
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_post_id', models.CharField(max_length=255, verbose_name='platform post ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('text', models.TextField(blank=True, default='', verbose_name='text')),
                ('title', models.TextField(blank=True, default='', verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('caption', models.TextField(blank=True, default='', verbose_name='caption')),
                ('transcription', models.TextField(blank=True, default='', verbose_name='transcription')),
                ('view_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='view count')),
                ('like_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='like count')),
                ('comment_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='comment count')),
                ('share_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='share count')),
                ('reactions', models.JSONField(blank=True, null=True, verbose_name='reactions')),
                ('user_snapshot', models.JSONField(blank=True, null=True, verbose_name='user snapshot')),
                ('raw', models.JSONField(verbose_name='raw payload')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='froide_evidencecollection.socialmediaaccount', verbose_name='account')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='froide_evidencecollection.socialmediapost', verbose_name='reply to')),
                ('quoted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_by', to='froide_evidencecollection.socialmediapost', verbose_name='quoted post')),
                ('repost_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='froide_evidencecollection.socialmediapost', verbose_name='repost of')),
            ],
            options={
                'verbose_name': 'social media post',
                'verbose_name_plural': 'social media posts',
            },
        ),
        migrations.AddConstraint(
            model_name='socialmediapost',
            constraint=models.UniqueConstraint(fields=('account', 'platform_post_id'), name='unique_post_per_account'),
        ),
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='froide_evidencecollection.socialmediapost', verbose_name='social media post')),
            ],
            options={
                'verbose_name': 'evidence source',
                'verbose_name_plural': 'evidence sources',
            },
        ),
        migrations.AddConstraint(
            model_name='evidencesource',
            constraint=models.CheckConstraint(condition=models.Q(('social_media_post__isnull', False)), name='evidence_source_target_required'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_set', to='froide_evidencecollection.evidencesource', verbose_name='source'),
        ),
    ]