# Generated by Django 5.2.13 on 2026-06-16 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0024_category_chapter_keyword_keywordgroup_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoexcerpt',
            name='video',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='originators',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='related_actors',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='topic_fit_at',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='topic_reassigned',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='topic_x',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='topic_y',
        ),
        migrations.RemoveField(
            model_name='postvideo',
            name='file',
        ),
        migrations.AddField(
            model_name='postvideo',
            name='timestamps',
            field=models.JSONField(blank=True, default=list, verbose_name='timestamps'),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='transcript',
            field=models.TextField(blank=True, default='', help_text='Full transcript (searched). Import-filled.', verbose_name='transcript'),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='transcript_override',
            field=models.TextField(blank=True, default='', help_text='Curator correction of the transcript. Blank falls back to the imported value. Preserved across re-imports.', verbose_name='transcript (corrected)'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='file',
            field=models.FileField(max_length=255, upload_to='post_media', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='postscreenshot',
            name='file',
            field=models.FileField(max_length=255, upload_to='post_media', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='transcript_file',
            field=models.FileField(blank=True, help_text='Original transcript file (e.g. SRT), kept as backup.', max_length=255, upload_to='post_media', verbose_name='transcript file'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text', models.TextField(blank=True, default='', help_text='Cited text (searched). Import-filled.', verbose_name='text')),
                ('text_override', models.TextField(blank=True, default='', help_text='Curator correction of the cited text. Blank falls back to the imported value. Preserved across re-imports.', verbose_name='text (corrected)')),
                ('is_full_source', models.BooleanField(default=False, help_text='The quote is the whole post: its topic uses the full source text and it is not rendered as a separate quote block.', verbose_name='is full source')),
                ('start', models.DurationField(blank=True, null=True, verbose_name='start')),
                ('end', models.DurationField(blank=True, null=True, verbose_name='end')),
                ('topic_x', models.FloatField(blank=True, null=True, verbose_name='topic x')),
                ('topic_y', models.FloatField(blank=True, null=True, verbose_name='topic y')),
                ('topic_fit_at', models.DateTimeField(blank=True, null=True, verbose_name='topic fitted at')),
                ('topic_reassigned', models.BooleanField(default=False, help_text='True if this quote was an HDBSCAN outlier in the most recent fit and was moved into its topic by outlier reduction, rather than being a core cluster member.', verbose_name='topic reassigned from outlier')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='froide_evidencecollection.evidence', verbose_name='evidence')),
                ('keywords', models.ManyToManyField(blank=True, related_name='quotes', to='froide_evidencecollection.keyword', verbose_name='keywords')),
                ('originators', models.ManyToManyField(blank=True, related_name='originated_quotes', to='froide_evidencecollection.actor', verbose_name='originators')),
                ('related_actors', models.ManyToManyField(blank=True, related_name='related_quotes', to='froide_evidencecollection.actor', verbose_name='related actors')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='froide_evidencecollection.topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'quote',
                'verbose_name_plural': 'quotes',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footnote', models.CharField(blank=True, default='', max_length=255, verbose_name='footnote')),
                ('chapter_structure', models.JSONField(default=list, verbose_name='chapter structure')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='froide_evidencecollection.category', verbose_name='category')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='froide_evidencecollection.chapter', verbose_name='chapter')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='froide_evidencecollection.quote', verbose_name='quote')),
            ],
            options={
                'verbose_name': 'reference',
                'verbose_name_plural': 'references',
                'ordering': ['footnote'],
            },
        ),
        migrations.DeleteModel(
            name='EvidenceMention',
        ),
        migrations.DeleteModel(
            name='VideoExcerpt',
        ),
    ]
