# Generated by Django 5.2.10 on 2026-04-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0024_populate_name_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('tiktok', 'TikTok'), ('x', 'X'), ('youtube', 'YouTube')], max_length=20, verbose_name='platform')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='froide_evidencecollection.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'social media account',
                'verbose_name_plural': 'social media accounts',
                'ordering': ('platform', 'username'),
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_evidence', to='froide_evidencecollection.socialmediaaccount', verbose_name='posted by'),
        ),
        migrations.AddConstraint(
            model_name='socialmediaaccount',
            constraint=models.UniqueConstraint(fields=('platform', 'username'), name='unique_social_media_account'),
        ),
    ]
