# Generated by Django 5.2.13 on 2026-06-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0025_socialmediaaccount_socialmediapost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Literal term (matched whole-word) or, if marked, a regex.', max_length=255, verbose_name='pattern')),
                ('is_regex', models.BooleanField(default=False, verbose_name='is regex')),
                ('placeholder', models.CharField(help_text='Replacement shown in place of the term, e.g. “[N-Wort]”.', max_length=100, verbose_name='placeholder')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('posts', models.ManyToManyField(blank=True, help_text='Leave empty for a global rule; otherwise scope to these posts.', related_name='redaction_rules', to='froide_evidencecollection.socialmediapost', verbose_name='posts')),
            ],
            options={
                'verbose_name': 'redaction rule',
                'verbose_name_plural': 'redaction rules',
                'ordering': ['pattern'],
            },
        ),
    ]
