# Generated by Django 5.2.10 on 2026-06-16 10:46

import froide_evidencecollection.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0025_alter_postimage_file_alter_postscreenshot_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='postscreenshot',
            name='file',
        ),
        migrations.RemoveField(
            model_name='postvideo',
            name='file',
        ),
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=froide_evidencecollection.storage.OverwriteStorage(), upload_to=froide_evidencecollection.storage.post_media_path, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='postscreenshot',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=froide_evidencecollection.storage.OverwriteStorage(), upload_to=froide_evidencecollection.storage.post_media_path, verbose_name='image'),
        ),
    ]
