# Generated by Django 5.2.10 on 2026-04-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0025_socialmediaaccount_evidence_posted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(verbose_name='page')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='froide_evidencecollection.category', verbose_name='category')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='froide_evidencecollection.evidence', verbose_name='evidence')),
            ],
            options={
                'verbose_name': 'evidence mention',
                'verbose_name_plural': 'evidence mentions',
                'ordering': ['page'],
            },
        ),
    ]
