# Generated by Django 5.2.13 on 2026-06-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0026_redactionrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=100, unique=True, verbose_name='lemma')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('surface_forms', models.JSONField(blank=True, default=dict, verbose_name='surface forms')),
                ('custom_label', models.CharField(blank=True, default='', max_length=100, verbose_name='custom label')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('df', models.PositiveIntegerField(default=0, verbose_name='document frequency')),
                ('salience_max', models.FloatField(default=0.0, verbose_name='max salience')),
                ('salience_mean', models.FloatField(default=0.0, verbose_name='mean salience')),
                ('fit_at', models.DateTimeField(verbose_name='fitted at')),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'ordering': ['label'],
            },
        ),
    ]
