# Generated by Django 5.2.13 on 2026-06-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0026_remove_postimage_file_remove_postscreenshot_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('evidences', models.ManyToManyField(blank=True, related_name='themes', to='froide_evidencecollection.evidence', verbose_name='directly assigned evidence')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='froide_evidencecollection.theme', verbose_name='theme'),
        ),
    ]
