# Generated by Django 5.2.10 on 2026-04-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0026_category_evidencemention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='profile_pic_url',
        ),
    ]
