# Generated by Django 5.2.13 on 2026-06-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0027_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('custom_label', models.CharField(max_length=255, verbose_name='label')),
                ('is_main_topic', models.BooleanField(default=False, verbose_name='is main topic')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
            },
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='attribution_evidence',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='attribution_justification',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='attribution_problems',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='legal_assessment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='primary_source_info',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='primary_source_url',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='publishing_date',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='reference_info',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='reference_url',
        ),
        migrations.AddField(
            model_name='evidence',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='evidences', to='froide_evidencecollection.keyword', verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='slug',
            field=models.SlugField(default='', max_length=10, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='social_media_post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='froide_evidencecollection.socialmediapost', verbose_name='social media post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='topic_fit_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='topic fitted at'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='topic_x',
            field=models.FloatField(blank=True, null=True, verbose_name='topic x'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='topic_y',
            field=models.FloatField(blank=True, null=True, verbose_name='topic y'),
        ),
        migrations.CreateModel(
            name='EvidenceMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footnote', models.CharField(blank=True, default='', max_length=255, verbose_name='footnote')),
                ('chapter_structure', models.JSONField(default=list, verbose_name='chapter structure')),
                ('citation', models.TextField(blank=True, default='', verbose_name='citation')),
                ('start', models.DurationField(blank=True, null=True, verbose_name='start')),
                ('end', models.DurationField(blank=True, null=True, verbose_name='end')),
                ('raw_transcript', models.TextField(blank=True, default='', verbose_name='raw transcript')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='froide_evidencecollection.category', verbose_name='category')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='froide_evidencecollection.chapter', verbose_name='chapter')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='froide_evidencecollection.evidence', verbose_name='evidence')),
            ],
            options={
                'verbose_name': 'evidence mention',
                'verbose_name_plural': 'evidence mentions',
                'ordering': ['footnote'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('evidences', models.ManyToManyField(blank=True, related_name='themes', to='froide_evidencecollection.evidence', verbose_name='directly assigned evidence')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='froide_evidencecollection.theme', verbose_name='theme'),
        ),
    ]
