# Generated by Django 5.2.13 on 2026-06-19 08:33

import froide_evidencecollection.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0027_theme_chapter_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postscreenshot',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postvideo',
            name='post',
        ),
        migrations.RemoveField(
            model_name='videoexcerpt',
            name='video',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='raw',
        ),
        migrations.AddField(
            model_name='evidencemention',
            name='end',
            field=models.DurationField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='evidencemention',
            name='raw_transcript',
            field=models.TextField(blank=True, default='', verbose_name='raw transcript'),
        ),
        migrations.AddField(
            model_name='evidencemention',
            name='start',
            field=models.DurationField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='image_description',
            field=models.TextField(blank=True, default='', help_text='Textual description (alt text) of what the image shows.', verbose_name='image description'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='image_source_path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='image source path'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='screenshot',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=froide_evidencecollection.storage.OverwriteStorage(), upload_to=froide_evidencecollection.storage.post_screenshot_path, verbose_name='screenshot'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='screenshot_source_path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='screenshot source path'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='transcription',
            field=models.TextField(blank=True, default='', help_text='Full verbatim video transcript; display/backup.', verbose_name='transcription'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='video_source_path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='video source path'),
        ),
        migrations.CreateModel(
            name='RedactionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Literal term (matched whole-word) or, if marked, a regex.', max_length=255, verbose_name='pattern')),
                ('is_regex', models.BooleanField(default=False, verbose_name='is regex')),
                ('placeholder', models.CharField(help_text='Replacement shown in place of the term, e.g. “[N-Wort]”.', max_length=100, verbose_name='placeholder')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('posts', models.ManyToManyField(blank=True, help_text='Leave empty for a global rule; otherwise scope to these posts.', related_name='redaction_rules', to='froide_evidencecollection.socialmediapost', verbose_name='posts')),
            ],
            options={
                'verbose_name': 'redaction rule',
                'verbose_name_plural': 'redaction rules',
                'ordering': ['pattern'],
            },
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.DeleteModel(
            name='PostScreenshot',
        ),
        migrations.DeleteModel(
            name='PostVideo',
        ),
        migrations.DeleteModel(
            name='VideoExcerpt',
        ),
    ]
