# Generated by Django 5.2.13 on 2026-04-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0027_remove_socialmediaaccount_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='froide_evidencecollection.actor', verbose_name='actor'),
        ),
    ]
