# Generated by Django 5.2.13 on 2026-06-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0028_category_chapter_and_more'),
        ('georegion', '0013_alter_georegion_region_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('type', models.CharField(choices=[('mandate', 'Mandate'), ('parliament', 'Parliament'), ('party', 'Party')], max_length=10, verbose_name='type')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('start_source_url', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='start date source URL')),
                ('end_source_url', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='end date source URL')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comment')),
                ('institutional_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='froide_evidencecollection.institutionallevel', verbose_name='institutional level')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='political_positions', to='froide_evidencecollection.organization', verbose_name='organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='political_positions', to='froide_evidencecollection.person', verbose_name='person')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georegion.georegion', verbose_name='region')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='froide_evidencecollection.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'political position',
                'verbose_name_plural': 'political positions',
            },
        ),
    ]
