# Generated by Django 5.2.10 on 2026-04-30 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0028_alter_socialmediaaccount_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='quoted',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='repost_of',
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('repost', 'Repost')], default='', max_length=16, verbose_name='reference type'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='references',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='froide_evidencecollection.socialmediapost', verbose_name='referenced post'),
        ),
    ]
