# Generated by Django 5.2.10 on 2026-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0029_remove_socialmediapost_quoted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='profile_retrieved_at',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='profile_url',
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='collected_at'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL'),
        ),
    ]
