# Generated by Django 5.2.13 on 2026-05-13 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0030_remove_socialmediaaccount_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceActorRelationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'evidence–actor relation role',
                'verbose_name_plural': 'evidence–actor relation roles',
            },
        ),
        migrations.CreateModel(
            name='EvidenceRelationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'evidence–evidence relation role',
                'verbose_name_plural': 'evidence–evidence relation roles',
            },
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='attribution_problems',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='related_actors',
        ),
        migrations.RemoveField(
            model_name='evidencesource',
            name='social_media_post',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='source',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='attribution_evidence',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='attribution_justification',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='legal_assessment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='originators',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='primary_source_info',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='primary_source_url',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='publishing_date',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='reference_info',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='reference_url',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='url_hash',
        ),
        migrations.AddField(
            model_name='evidence',
            name='social_media_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='froide_evidencecollection.socialmediapost', verbose_name='social media post'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(max_length=255, upload_to='documents', verbose_name='file')),
                ('url', models.URLField(blank=True, default='', help_text='Original URL where the document was obtained, if any.', max_length=500, verbose_name='source URL')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='published at')),
                ('text', models.TextField(blank=True, default='', help_text='Plain-text content (OCR or extraction).', verbose_name='extracted text')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='collected at')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_documents', to='froide_evidencecollection.actor', verbose_name='issuer')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='froide_evidencecollection.document', verbose_name='document'),
        ),
        migrations.CreateModel(
            name='EvidenceActorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_relations', to='froide_evidencecollection.actor', verbose_name='actor')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_relations', to='froide_evidencecollection.evidence', verbose_name='evidence')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='froide_evidencecollection.evidenceactorrelationrole', to_field='name', verbose_name='role')),
            ],
            options={
                'verbose_name': 'evidence–actor relation',
                'verbose_name_plural': 'evidence–actor relations',
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='related_actors',
            field=models.ManyToManyField(related_name='related_evidence', through='froide_evidencecollection.EvidenceActorRelation', through_fields=('evidence', 'actor'), to='froide_evidencecollection.actor', verbose_name='related actors'),
        ),
        migrations.CreateModel(
            name='EvidenceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='froide_evidencecollection.evidence', verbose_name='from evidence')),
                ('to_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='froide_evidencecollection.evidence', verbose_name='to evidence')),
            ],
            options={
                'verbose_name': 'evidence–evidence relation',
                'verbose_name_plural': 'evidence–evidence relations',
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='related_evidence',
            field=models.ManyToManyField(through='froide_evidencecollection.EvidenceRelation', through_fields=('from_evidence', 'to_evidence'), to='froide_evidencecollection.evidence', verbose_name='related evidence'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', True), ('social_media_post__isnull', False)), models.Q(('document__isnull', False), ('social_media_post__isnull', True)), _connector='OR'), name='evidence_exactly_one_source'),
        ),
        migrations.AddField(
            model_name='evidencerelation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='froide_evidencecollection.evidencerelationrole', to_field='name', verbose_name='role'),
        ),
        migrations.DeleteModel(
            name='AttributionProblem',
        ),
        migrations.DeleteModel(
            name='EvidenceSource',
        ),
        migrations.AddConstraint(
            model_name='evidenceactorrelation',
            constraint=models.UniqueConstraint(fields=('evidence', 'actor', 'role'), name='unique_evidence_actor_role'),
        ),
        migrations.AddConstraint(
            model_name='evidenceactorrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'posted_by')), fields=('evidence',), name='one_posted_by_per_evidence'),
        ),
        migrations.AddConstraint(
            model_name='evidencerelation',
            constraint=models.UniqueConstraint(fields=('from_evidence', 'to_evidence', 'role'), name='unique_evidence_evidence_role'),
        ),
        migrations.AddConstraint(
            model_name='evidencerelation',
            constraint=models.CheckConstraint(condition=models.Q(('from_evidence', models.F('to_evidence')), _negated=True), name='no_evidence_self_relation'),
        ),
    ]
