# Generated by Django 5.2.13 on 2026-06-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0031_evidencemention_originator'),
        ('georegion', '0013_alter_georegion_region_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verband',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind__in': ['state', 'country']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='georegion.georegion', verbose_name='Verband'),
        ),
        migrations.AddField(
            model_name='person',
            name='verband',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind__in': ['state', 'country']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='georegion.georegion', verbose_name='Verband'),
        ),
    ]
