# Generated by Django 5.2.13 on 2026-05-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0032_seed_evidence_relation_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceactorrelationrole',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Curator override; leave blank to use the translated default.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='evidencerelationrole',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Curator override; leave blank to use the translated default.', verbose_name='description'),
        ),
    ]
