# Generated by Django 5.2.13 on 2026-06-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0032_organization_verband_person_verband'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicalposition',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='politicalposition',
            name='end_source_url',
        ),
        migrations.RemoveField(
            model_name='politicalposition',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='politicalposition',
            name='region',
        ),
        migrations.RemoveField(
            model_name='politicalposition',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='politicalposition',
            name='start_source_url',
        ),
        migrations.RemoveField(
            model_name='politicalposition',
            name='type',
        ),
    ]
