# Generated by Django 5.2.15 on 2026-06-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        (
            "froide_evidencecollection",
            "0033_remove_politicalposition_end_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicCloudCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
            ],
            options={
                "verbose_name": "topic cloud",
            },
            bases=("cms.cmsplugin",),
        ),
    ]
