# Generated by Django 5.2.10 on 2026-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0033_alter_evidenceactorrelationrole_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importexportrun',
            name='source',
            field=models.CharField(choices=[('FE', 'Froide EvidenceCollection'), ('NC', 'NocoDB'), ('AW', 'abgeordnetenwatch.de'), ('WD', 'Wikidata'), ('JS', 'JSON dump')], max_length=2, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='importexportrun',
            name='target',
            field=models.CharField(choices=[('FE', 'Froide EvidenceCollection'), ('NC', 'NocoDB'), ('AW', 'abgeordnetenwatch.de'), ('WD', 'Wikidata'), ('JS', 'JSON dump')], max_length=2, verbose_name='target'),
        ),
    ]
