# Generated by Django 5.2.13 on 2026-05-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0034_alter_importexportrun_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencerelation',
            name='from_evidence',
        ),
        migrations.RemoveField(
            model_name='evidencerelation',
            name='role',
        ),
        migrations.RemoveField(
            model_name='evidencerelation',
            name='to_evidence',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='related_evidence',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='reference_type',
        ),
        migrations.RenameField(
            model_name='socialmediapost',
            old_name='references',
            new_name='redistributes',
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='redistributes',
            field=models.ForeignKey(blank=True, help_text='Post whose content this post redistributes (repost, quote, forward, …).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redistributed_by', to='froide_evidencecollection.socialmediapost', verbose_name='redistributed post'),
        ),
        migrations.DeleteModel(
            name='EvidenceRelationRole',
        ),
        migrations.DeleteModel(
            name='EvidenceRelation',
        ),
    ]
