# Generated by Django 5.2.13 on 2026-06-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0034_topiccloudcmsplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencemention',
            name='report_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='report URL'),
        ),
    ]
