# Generated by Django 5.2.13 on 2026-07-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0035_evidencemention_report_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
