# Generated by Django 5.2.13 on 2026-05-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0035_remove_evidencerelation_from_evidence_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialmediaaccount',
            name='unique_social_media_account',
        ),
        migrations.AddConstraint(
            model_name='socialmediaaccount',
            constraint=models.UniqueConstraint(fields=('platform', 'platform_user_id'), name='unique_social_media_account'),
        ),
    ]
