# Generated by Django 5.2.13 on 2026-07-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0036_remove_chapter_theme_delete_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
