# Generated by Django 5.2.13 on 2026-07-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0037_remove_evidence_keywords_delete_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencemention',
            name='raw_transcript',
        ),
    ]
