# Generated by Django 5.2.13 on 2026-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0038_remove_evidencemention_raw_transcript'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evidencemention',
            constraint=models.UniqueConstraint(fields=('evidence', 'footnote'), name='unique_footnote_per_evidence'),
        ),
    ]
