# Generated by Django 5.2.13 on 2026-07-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0039_evidencemention_unique_footnote_per_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencemention',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
