# Generated by Django 5.2.13 on 2026-07-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0040_remove_evidencemention_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='last_synced_state',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='last_synced_state',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_synced_state',
        ),
        migrations.RemoveField(
            model_name='person',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='last_synced_state',
        ),
        migrations.RemoveField(
            model_name='role',
            name='synced_at',
        ),
    ]
