# Generated by Django 5.2.13 on 2026-07-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0041_remove_affiliation_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='status',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.DeleteModel(
            name='OrganizationStatus',
        ),
        migrations.DeleteModel(
            name='PersonStatus',
        ),
    ]
