# Generated by Django 5.2.13 on 2026-07-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0042_remove_organization_status_remove_person_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='special_regions',
        ),
    ]
