# Generated by Django 5.2.13 on 2026-07-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0043_remove_organization_regions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='evidence',
        ),
        migrations.DeleteModel(
            name='AttributionProblem',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
