# Generated by Django 5.2.13 on 2026-07-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0044_remove_attachment_evidence_delete_attributionproblem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='evidence_type',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='description',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='EvidenceType',
        ),
    ]
