# Generated by Django 5.2.13 on 2026-07-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0045_remove_evidence_collections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='related_actors',
        ),
    ]
