# Generated by Django 5.2.15 on 2026-07-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_evidencecollection', '0048_thin_political_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='transcription',
            field=models.TextField(blank=True, default='', help_text='Full verbatim video transcript; kept as backup only.', verbose_name='transcription'),
        ),
    ]
